plugins {
	id 'java'
	id 'application'
	id 'jacoco'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation 'org.assertj:assertj-core:3.27.7'
	testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
	testLogging {
		events 'passed', 'failed'
	}
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		html.required = true
		xml.required = true
	}
}

application {
	mainClass = 'ch.bbw.m450.tictactoe.TicTacToeMain'
}

run {
	standardInput = System.in
}
