name: build

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flashbibi/450-tictactest-mvk:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v7

      - name: Kompilieren, ohne Tests
        run: ./gradlew assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flashbibi/450-tictactest-mvk:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v7

      - name: Tests ausfuehren
        run: ./gradlew test
