name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: JDK bereitstellen
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 25

      - name: Gradle einrichten
        uses: gradle/actions/setup-gradle@v6

      - name: Build und Tests
        run: ./gradlew build
